acre2:
  - addons/acre2/**/*
adminmenu:
- addons/adminmenu/**/*
ai:
- addons/ai/**/*
assigngear:
- addons/assigngear/**/*
autotest:
- addons/autotest/**/*
briefing:
- addons/briefing/**/*
cascap:
- addons/cascap/**/*
chat:
- addons/chat/**/*
common:
- addons/common/**/*
debrief:
- addons/debrief/**/*
event:
- addons/event/**/*
main:
- addons/main/**/*
marker:
- addons/marker/**/*
orbat:
- addons/orbat/**/*
patrol:
- addons/patrol/**/*
respawn:
- addons/respawn/**/*
safestart:
- addons/safestart/**/*
spectator:
- addons/spectator/**/*
teamcolour:
- addons/teamcolour/**/*
teleport:
- addons/teleport/**/*
zeus:
- addons/zeus/**/*
