class cfgFunctions {
    class ADDON {
        class COMPONENT {
            file = QPATHTO_FOLDER(functions);
            class debugError;
            class debugLog;
            class debugMsg;
            class dummy;
            class numToColor;
            class getCfgEntry;
            class getCfgEntryFromPath;
            class numToSide;
            class numToTexture;
            class sideToNum;
            class sideToString;
            class sideToColor;
            class sideToHexColor;
            class sideToTexture;
            class sideType;
            class evaluateCondArray;
            class isAdmin;
            class capitalize;
            class initGroupVar;
            class checkJIP;
            class handleLocalJip;
            class getNearestRoad;
            class serializeWaypoint;
            class serializeWaypoints;
            class moduleUnits;
            class checkVersionArray;
            class checkTMFVersion;
            class arrayToStringArray;
            class randPosArea;
            class drawLines;
            class endMission;
            class edenMouseOver;
            class edenMouseKeyDown;
            class edenMouseKeyUp;
            class edenInit;
            class edenDraw;
        };
    };
};
