#define IDC_SPECTATOR_TMF_SPECTATOR_UNITLABEL    4945
#define IDC_SPECTATOR_TMF_SPECTATOR_UNITLIST    7171
#define IDC_SPECTATOR_TMF_SPECTATOR_VISION    5545
#define IDC_SPECTATOR_TMF_SPECTATOR_FILTER    5546
#define IDC_SPECTATOR_TMF_SPECTATOR_BUTTON    5547
#define IDC_SPECTATOR_TMF_SPECTATOR_TAGS    5548
#define IDC_SPECTATOR_TMF_SPECTATOR_VIEW    5549

#define IDC_SPECTATOR_TMF_SPECTATOR_COMPASS        5453
#define IDC_SPECTATOR_TMF_SPECTATOR_COMPASSLEFT        5454
#define IDC_SPECTATOR_TMF_SPECTATOR_COMPASSRight        5455
#define IDC_SPECTATOR_TMF_SPECTATOR_MUTE 5467
#define IDC_SPECTATOR_TMF_SPECTATOR_MAP 5468


#define IDC_SPECTATOR_TMF_SPECTATOR_MENUBACK    6145
#define IDC_SPECTATOR_TMF_SPECTATOR_DIALOG    5454
