name: PR checker
# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
jobs:
  check:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Check config style
      run: python3 tools/config_style_checker.py
